formatter: markdown table
# header-from: ../docs/header.md
output:
  file: "./README.md"
  mode: replace
  template: |-
    # terraform-aws-cloudfront

    Terraform module to create CloudFront Distribution

    {{ .Content }}

sections:
  hide-all: true
  show:
    - header
    - inputs
    - outputs
    - providers
    - resources

sort:
  enabled: true
  by: required